config/routes.rb
Rails.application.routes.draw do
  # get '/games/new', to: 'games#new'
  # post '/games', to:'games#create'
  #get '/games/new', to: 'games#new'
  #get '/games/edit', to: 'games#edit'
  # patch	'/games', to: 'games#update'
  # delete '/games', to:'games#destroy'
  get 'sessions/new'

  get 'gamesone', to: 'games#index'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
###################################################################

  get 'welcome', to: 'welcome#index'
  #get 'welcome/index'
  #root 'welcome#index'
  get 'games', to: 'games#new'
  get 'games/new', to: 'games#new'
  get 'games/play/:id', to: "games#play"
  resources :games
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Help | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
<!--   <div id='ticfirst'>
    <h1>Tic Tac Toe</h1>
  </div> -->
 <br>
</div>
<div class="imgB">
<% if logged_in? %>
<%= link_to "Games", 'gamesone', method: :get , class: "btn btn-lg btn-primary" %>
<%= link_to "Games Multiplayer", welcome_path , method: :get, class: "btn btn-lg btn btn-info " %>
<% else %>
<div class="imgA">
<%= link_to "Sign up", signup_path, method: :get , class: "btn btn-lg btn btn-success" %></div>
<% end %>
 <!-- <%= image_tag("intro.jpg") %>  -->
 </div>
 <!--tuk -->

<!-- <br><br>
<iframe id="iframe" width="560" height="315" src="https://www.youtube.com/embed/WUX0hB1u0vE" frameborder="0" allowfullscreen></iframe>
  <div class="supporting">
      <div class="container">
        <h2>A world of games at your fingertips.</h2>
      
        <div class="row">
          <div class="col-md-6">
            <div class="thumbnail">
            <%= image_tag("1468.jpg") %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="thumbnail">
            <%= image_tag("7.jpg") %>
            
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="thumbnail">
    
              <%= image_tag("4.jpg") %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="thumbnail">
              <%= image_tag("222.jpg") %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="thumbnail">
              <%= image_tag("4a.jpg") %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="thumbnail">
    
              <%= image_tag("122.jpg") %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="thumbnail">
              <%= image_tag("9uf.jpg") %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="thumbnail">
              <%= image_tag("intro1.jpg") %>
            </div>
          </div>
        </div>

        <!-- <div class="row">
          <div class="col-md-4">
            <div class="thumbnail">
         
              <%= image_tag("122.jpg") %>
            </div>
          </div> -->
        <!--   <div class="col-md-4">
            <div class="thumbnail">
        
              <%= image_tag("2.jpg") %>
            </div>
          </div> -->
         <!--  <div class="col-md-4">
            <div class="thumbnail">
             
              <%= image_tag("9.jpg") %>
            </div>
          </div> -->
      <!--     <div class="col-md-4">
            <div class="thumbnail">
             
              <%= image_tag("1.jpg") %>
            </div>
          </div> -->
        </div>
      </div>
    </div> 
 <!-- do tuk -->
 <div class="feature">
      <div class="container">
        <!-- <h1>Mobile version</h1> -->
        <p></p>
      </div>
    </div> 
  </body>
</html>