config/routes.rb
Rails.application.routes.draw do
  # get '/games/new', to: 'games#new'
  # post '/games', to:'games#create'
  #get '/games/new', to: 'games#new'
  #get '/games/edit', to: 'games#edit'
  # patch	'/games', to: 'games#update'
  # delete '/games', to:'games#destroy'
  get 'sessions/new'

  get 'gamesone', to: 'games#index'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
###################################################################

  get 'welcome', to: 'welcome#index'
  #get 'welcome/index'
  #root 'welcome#index'
  get 'games', to: 'games#new'
  get 'games/new', to: 'games#new'
  get 'games/play/:id', to: "games#play"
  resources :games
end

app/views/layouts/_footer.html.erb
<div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <h3>Bolt</h3>
            <ul>
              <li><%= link_to "Help", help_path %></li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3>More</h3>
            <ul>
              <li><a href="http://www.datecs.bg/"> Datecs</a></li></a>
            </ul>
          </div>
          <div class="col-md-3">
            <h3>News</h3>
            <ul>
              <li><a href="https://www.youtube.com/">YouTube</a></li>
              <br>
            </ul>
          </div>
        </div>
      </div>
    </div>

              

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-lighth" style="background-color: #333;"> <!-- "navbar navbar-fixed-top navbar-inverse"-->
  <div class="container">
     <!--  <%= link_to "sample app", '#', id: "logo" %> -->
     <%= image_tag("Logomakr_4p2nVB.png", id:"logo") %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <!--<li><%= link_to "Help", help_path %></li>-->
        <% if logged_in? %>
       <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
           <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu"> -->
              <li><%= link_to "Profile", current_user %></li>
           <!--    <li><%= link_to "Settings", edit_user_path(current_user) %></li> -->
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
           <!--  </ul> -->
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= render 'layouts/shim' %>
  </head>
  <body>
    
    <div class="container">
    <%= render 'layouts/header' %>
      <%= yield %>  

    </div> 
<%= render 'layouts/footer' %> 
  </body>
    
</html>